.DEFAULT_GOAL := help

.PHONY: help \
        forge-install-claude-project-copy anvil-install-claude-project-copy \
        forge-install-codex-project-copy anvil-install-codex-project-copy \
        connect_gemini disconnect_gemini connect_serena disconnect_serena

help:
	@echo "Usage: make <target> DIR=/path/to/project"
	@echo ""
	@echo "プラグイン直接インストール（プラグイン機構が使えない環境向け・copy 方式）:"
	@echo "  make forge-install-claude-project-copy DIR=dir   forge を <dir>/.claude/ へ配置"
	@echo "  make anvil-install-claude-project-copy DIR=dir   anvil を <dir>/.claude/ へ配置"
	@echo "  make forge-install-codex-project-copy  DIR=dir   forge を <dir>/.agents/ + <dir>/.codex/ へ配置"
	@echo "  make anvil-install-codex-project-copy  DIR=dir   anvil を <dir>/.agents/ + <dir>/.codex/ へ配置"
	@echo "  実ファイルをコピーする。DIR は必須（既定値なし）"
	@echo "  両ツールで使う場合は claude 用と codex 用を順に実行"
	@echo "  自動 uninstall は提供しない。削除は git rm -r で行う"
	@echo ""
	@echo "MCP サーバー操作:"
	@echo "  make connect_gemini          - Connect gemini-cli MCP server to Claude Code"
	@echo "  make disconnect_gemini       - Disconnect gemini-cli MCP server from Claude Code"
	@echo "  make connect_serena          - Connect serena MCP server to Claude Code"
	@echo "  make disconnect_serena       - Disconnect serena MCP server from Claude Code"

# -----------------------------------------------------------------------
# プラグイン直接インストール（copy 方式）
# Generated by /plugin-installer-creator — 再生成: このプロジェクトで /plugin-installer-creator を実行
# -----------------------------------------------------------------------
forge-install-claude-project-copy:
	@[ -n "$(DIR)" ] || { echo "Error: DIR is required: make $@ DIR=/path/to/project" >&2; exit 1; }
	@bash scripts/plugin-installer/install_copy.sh forge "$(DIR)"

anvil-install-claude-project-copy:
	@[ -n "$(DIR)" ] || { echo "Error: DIR is required: make $@ DIR=/path/to/project" >&2; exit 1; }
	@bash scripts/plugin-installer/install_copy.sh anvil "$(DIR)"

forge-install-codex-project-copy:
	@[ -n "$(DIR)" ] || { echo "Error: DIR is required: make $@ DIR=/path/to/project" >&2; exit 1; }
	@bash scripts/plugin-installer/install_copy_codex.sh forge "$(DIR)"

anvil-install-codex-project-copy:
	@[ -n "$(DIR)" ] || { echo "Error: DIR is required: make $@ DIR=/path/to/project" >&2; exit 1; }
	@bash scripts/plugin-installer/install_copy_codex.sh anvil "$(DIR)"

connect_gemini:
	@echo "Connecting gemini-cli MCP server to Claude Code..."
	claude mcp add gemini-cli -s user -- npx -y gemini-mcp-tool

disconnect_gemini:
	@echo "Disconnecting gemini-cli MCP server from Claude Code..."
	claude mcp remove gemini-cli

connect_serena:
	@if [ -n "$$SERENA_PATH" ]; then \
		echo "Connecting local serena from $$SERENA_PATH to Claude Code..."; \
		claude mcp add serena -- uv run --directory $$SERENA_PATH serena-mcp-server --project $$PWD; \
	else \
		echo "❌ No local serena"; \
	fi

disconnect_serena:
	@echo "Disconnecting serena MCP server from Claude Code..."
	claude mcp remove serena
