.PHONY: help \
        install-forge install-anvil install-all \
        install-forge-codex install-anvil-codex install-all-codex \
        uninstall-forge uninstall-anvil \
        connect_gemini disconnect_gemini connect_serena disconnect_serena

# パス引数を取得（例: make install-all /path/to/project）
_ARGS := $(filter-out install-forge install-anvil install-all install-forge-codex install-anvil-codex install-all-codex uninstall-forge uninstall-anvil,$(MAKECMDGOALS))

default: help

help:
	@echo "プラグイン直接インストール（プラグイン機構が使えない環境向け）:"
	@echo "  make install-forge        [dir]  forge をインストール（Claude Code 専用）"
	@echo "  make install-anvil        [dir]  anvil をインストール（Claude Code 専用）"
	@echo "  make install-all          [dir]  全プラグインをインストール（Claude Code 専用）"
	@echo "  make install-forge-codex  [dir]  forge をインストール（Codex 専用）"
	@echo "  make install-anvil-codex  [dir]  anvil をインストール（Codex 専用）"
	@echo "  make install-all-codex    [dir]  全プラグインをインストール（Codex 専用）"
	@echo "  実体は .plugins/ に配置。Claude Code は .claude/skills/、Codex は .agents/skills/ からシンボリックリンクで参照"
	@echo "  両ツールで使う場合は install-xxx と install-xxx-codex を順に実行（.plugins/ は共有）"
	@echo "  make uninstall-forge      [dir]  forge を削除（.claude/skills/ と .agents/skills/ 両方のリンクを削除）"
	@echo "  make uninstall-anvil      [dir]  anvil を削除"
	@echo "  dir 省略時はカレントディレクトリにインストール"
	@echo ""
	@echo "MCP サーバー操作:"
	@echo "  make connect_gemini          - Connect gemini-cli MCP server to Claude Code"
	@echo "  make disconnect_gemini       - Disconnect gemini-cli MCP server from Claude Code"
	@echo "  make connect_serena          - Connect serena MCP server to Claude Code"
	@echo "  make disconnect_serena       - Disconnect serena MCP server from Claude Code"

# -----------------------------------------------------------------------
# プラグイン直接インストール
# Generated by /plugin-installer-creator — 再生成: このプロジェクトで /plugin-installer-creator を実行
# -----------------------------------------------------------------------
install-forge:
	@bash scripts/install_plugin.sh forge "$(_ARGS)"

install-anvil:
	@bash scripts/install_plugin.sh anvil "$(_ARGS)"

install-all: install-forge install-anvil

install-forge-codex:
	@bash scripts/install_plugin.sh --codex forge "$(_ARGS)"

install-anvil-codex:
	@bash scripts/install_plugin.sh --codex anvil "$(_ARGS)"

install-all-codex: install-forge-codex install-anvil-codex

uninstall-forge:
	@bash scripts/uninstall_plugin.sh forge "$(_ARGS)"

uninstall-anvil:
	@bash scripts/uninstall_plugin.sh anvil "$(_ARGS)"

# パス引数をターゲットとして解釈させないためのキャッチオール
%:
	@:

connect_gemini:
	@echo "Connecting gemini-cli MCP server to Claude Code..."
	claude mcp add gemini-cli -s user -- npx -y gemini-mcp-tool

disconnect_gemini:
	@echo "Disconnecting gemini-cli MCP server from Claude Code..."
	claude mcp remove gemini-cli

connect_serena:
	@if [ -n "$$SERENA_PATH" ]; then \
		echo "Connecting local serena from $$SERENA_PATH to Claude Code..."; \
		claude mcp add serena -- uv run --directory $$SERENA_PATH serena-mcp-server --project $$PWD; \
	else \
		echo "❌ No local serena"; \
	fi

disconnect_serena:
	@echo "Disconnecting serena MCP server from Claude Code..."
	claude mcp remove serena