#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ToC エントリ抽出スクリプト (doc-advisor plugin)

指定したパス群に対応する ToC エントリだけを抽出した YAML を stdout に出力する。
auto モード（query-rules / query-specs）で 100 件超の ToC をフィルタ Read する用途。

Usage:
    python3 filter_toc.py --category {specs|rules} --paths "path1,path2,..."

Options:
    --category   対象カテゴリ（必須）: specs または rules
    --paths      フィルタ対象のパスをカンマ区切りで指定（必須）

Run from: プロジェクトルート
"""

import argparse
import json
import sys
from datetime import datetime, timezone

from toc_utils import (
    ConfigNotReadyError,
    init_common_config,
    load_config,
    load_existing_toc,
    normalize_path,
    resolve_config_path,
    yaml_escape,
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="ToC YAML から指定パスのエントリだけを抽出する"
    )
    parser.add_argument(
        "--category",
        required=True,
        choices=["rules", "specs"],
        help="対象カテゴリ: rules または specs",
    )
    parser.add_argument(
        "--paths",
        required=True,
        help="フィルタ対象のパスをカンマ区切りで指定",
    )
    return parser.parse_args()


def get_toc_path(category, project_root, common_config):
    """ToC YAML のパスを返す（merge_toc.py と同じ解決規則）。"""
    config = load_config(category)
    default = f"{category}_toc.yaml"
    toc_file = config.get('toc_file', default)
    first_dir = common_config['first_dir']
    return resolve_config_path(toc_file, first_dir, project_root)


def render_subset_yaml(category, filtered_docs, original_count, requested_paths):
    """フィルタ済み docs を YAML として返す。

    Args:
        category: 'rules' または 'specs'
        filtered_docs: source_file → entry_dict（要求パスのうち ToC に存在したもの）
        original_count: 元の ToC のエントリ数
        requested_paths: 要求された全パス（存在チェック・統計用）

    Returns:
        str: YAML 文字列（末尾改行付き）
    """
    missing = sorted(p for p in requested_paths if p not in filtered_docs)

    lines = []
    toc_rel_path = f".claude/doc-advisor/toc/{category}/{category}_toc.yaml"
    lines.append(f"# Filtered subset of {toc_rel_path}")
    lines.append(
        f"# Generated by filter_toc.py at "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}"
    )
    lines.append(
        f"# Original entries: {original_count}, "
        f"Filtered entries: {len(filtered_docs)}, "
        f"Missing entries: {len(missing)}"
    )
    lines.append("")

    lines.append("metadata:")
    lines.append(f"  name: {yaml_escape(f'Filtered ToC Subset ({category})')}")
    lines.append(f"  filtered_count: {len(filtered_docs)}")
    lines.append(f"  original_count: {original_count}")
    lines.append(f"  missing_count: {len(missing)}")
    if missing:
        lines.append("  missing_paths:")
        for path in missing:
            lines.append(f"    - {yaml_escape(path)}")
    lines.append("")

    lines.append("docs:")
    if not filtered_docs:
        lines.append("  {}")
    else:
        for source_file, entry in sorted(filtered_docs.items()):
            lines.append(f"  {yaml_escape(source_file)}:")
            if 'doc_type' in entry:
                lines.append(f"    doc_type: {entry['doc_type']}")
            for key in ('title', 'purpose'):
                if key in entry:
                    lines.append(f"    {key}: {yaml_escape(entry[key])}")
            for key in ('content_details', 'applicable_tasks', 'keywords'):
                if key in entry and entry[key]:
                    lines.append(f"    {key}:")
                    for item in entry[key]:
                        lines.append(f"      - {yaml_escape(item)}")

    return '\n'.join(lines) + '\n'


def main():
    args = parse_args()

    paths = [normalize_path(p.strip()) for p in args.paths.split(',') if p.strip()]
    if not paths:
        print(json.dumps({
            "status": "error",
            "error": "--paths must contain at least one non-empty path.",
        }))
        sys.exit(1)

    try:
        common_config = init_common_config(args.category)
    except ConfigNotReadyError as e:
        print(json.dumps({"status": "error", "error": str(e)}))
        sys.exit(1)
    except (RuntimeError, FileNotFoundError) as e:
        print(json.dumps({"status": "error", "error": str(e)}))
        sys.exit(1)

    project_root = common_config['project_root']
    toc_path = get_toc_path(args.category, project_root, common_config)
    if not toc_path.exists():
        print(json.dumps({
            "status": "error",
            "error": f"ToC not found: {toc_path}. Run create-{args.category}-toc first.",
        }))
        sys.exit(1)

    docs = load_existing_toc(toc_path)
    requested = list(dict.fromkeys(paths))
    filtered = {p: docs[p] for p in requested if p in docs}

    sys.stdout.write(
        render_subset_yaml(args.category, filtered, len(docs), requested)
    )


if __name__ == "__main__":
    main()
