#!/usr/bin/env bash
# Generated by /plugin-installer-creator — 再生成: このプロジェクトで /plugin-installer-creator を実行
#
# プラグインをターゲットプロジェクトに直接インストールする。
# プラグイン機構が使えない環境向け。
#
# Usage: install_plugin.sh <plugin_name> [target_dir]
#   plugin_name : インストールするプラグイン名（例: forge, anvil）
#   target_dir  : インストール先プロジェクトルート（省略時: カレントディレクトリ）
#
# インストール方式:
#   1. plugins/{plugin}/ を {target}/.claude/plugins/{plugin}/ にコピー
#   2. ${CLAUDE_PLUGIN_ROOT} / ${CLAUDE_SKILL_DIR} を実パスに置換（Python 使用）
#   3. .claude/skills/{plugin}:{skill} → ../plugins/{plugin}/skills/{skill}/ のシンボリックリンクを作成

set -euo pipefail

# -----------------------------------------------------------------------
# 引数チェック
# -----------------------------------------------------------------------
PLUGIN_NAME="${1:-}"
TARGET_DIR="${2:-.}"

if [ -z "${PLUGIN_NAME}" ]; then
    echo "Usage: install_plugin.sh <plugin_name> [target_dir]" >&2
    echo "  plugin_name: forge | anvil | ..." >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PLUGIN_SRC="${REPO_ROOT}/plugins/${PLUGIN_NAME}"

if [ ! -d "${PLUGIN_SRC}" ]; then
    echo "Error: Plugin '${PLUGIN_NAME}' not found at ${PLUGIN_SRC}" >&2
    exit 1
fi

TARGET_DIR="$(cd "${TARGET_DIR}" && pwd)"
INSTALL_PATH=".claude/plugins/${PLUGIN_NAME}"
PLUGIN_DST="${TARGET_DIR}/${INSTALL_PATH}"
SKILLS_DIR="${TARGET_DIR}/.claude/skills"

# -----------------------------------------------------------------------
# 既存インストールの確認
# -----------------------------------------------------------------------
if [ -d "${PLUGIN_DST}" ]; then
    echo "Plugin '${PLUGIN_NAME}' is already installed in ${TARGET_DIR}"
    printf "Overwrite? [y/N] "
    read -r answer
    case "${answer}" in
        [yY]|[yY][eE][sS]) ;;
        *) echo "Aborted."; exit 0 ;;
    esac
fi

echo "Installing '${PLUGIN_NAME}' → ${TARGET_DIR}"

# -----------------------------------------------------------------------
# Step 1: プラグインファイルをコピー（メタデータ・キャッシュを除く）
# -----------------------------------------------------------------------
mkdir -p "${PLUGIN_DST}"

if command -v rsync &>/dev/null; then
    rsync -a \
        --exclude='.claude-plugin' \
        --exclude='__pycache__' \
        --exclude='.DS_Store' \
        --exclude='*.pyc' \
        "${PLUGIN_SRC}/" "${PLUGIN_DST}/"
else
    cp -r "${PLUGIN_SRC}/." "${PLUGIN_DST}/"
    find "${PLUGIN_DST}" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true
    find "${PLUGIN_DST}" -name '*.pyc' -delete 2>/dev/null || true
    find "${PLUGIN_DST}" -name '.DS_Store' -delete 2>/dev/null || true
    rm -rf "${PLUGIN_DST}/.claude-plugin"
fi

# -----------------------------------------------------------------------
# Step 2: ${CLAUDE_PLUGIN_ROOT} を実パスに置換
#         対象: .md / .yaml / .sh / .toml （Python で処理）
# -----------------------------------------------------------------------
python3 - "${PLUGIN_DST}" "${INSTALL_PATH}" <<'PYEOF'
import sys
import pathlib

plugin_dst = pathlib.Path(sys.argv[1])
install_path = sys.argv[2]
placeholder = "${CLAUDE_PLUGIN_ROOT}"
replaced = 0

for fpath in plugin_dst.rglob("*"):
    if not fpath.is_file():
        continue
    if fpath.suffix not in (".md", ".yaml", ".sh", ".toml"):
        continue
    # キャッシュ除外
    if "__pycache__" in fpath.parts:
        continue
    try:
        content = fpath.read_text(encoding="utf-8")
        if placeholder in content:
            fpath.write_text(content.replace(placeholder, install_path), encoding="utf-8")
            replaced += 1
    except Exception:
        pass

print(f"  CLAUDE_PLUGIN_ROOT replaced in {replaced} file(s)")
PYEOF

# -----------------------------------------------------------------------
# Step 3: ${CLAUDE_SKILL_DIR} をスキルごとの実パスに置換
#         スキルの SKILL.md のみ対象
# -----------------------------------------------------------------------
SKILLS_SRC="${PLUGIN_DST}/skills"

if [ -d "${SKILLS_SRC}" ]; then
    python3 - "${SKILLS_SRC}" "${INSTALL_PATH}" <<'PYEOF'
import sys
import pathlib

skills_src = pathlib.Path(sys.argv[1])
install_path = sys.argv[2]
placeholder = "${CLAUDE_SKILL_DIR}"
replaced = 0

for skill_dir in sorted(skills_src.iterdir()):
    if not skill_dir.is_dir():
        continue
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        continue
    skill_path = f"{install_path}/skills/{skill_dir.name}"
    content = skill_md.read_text(encoding="utf-8")
    if placeholder in content:
        skill_md.write_text(content.replace(placeholder, skill_path), encoding="utf-8")
        replaced += 1

print(f"  CLAUDE_SKILL_DIR replaced in {replaced} SKILL.md file(s)")
PYEOF
fi

# -----------------------------------------------------------------------
# Step 4: .claude/skills/{skill} → ../plugins/{plugin}/skills/{skill}/
#         のシンボリックリンクを作成（スキル名のみ、プレフィックスなし）
# -----------------------------------------------------------------------
mkdir -p "${SKILLS_DIR}"
SKILL_COUNT=0

if [ -d "${SKILLS_SRC}" ]; then
    for skill_dir in "${SKILLS_SRC}"/*/; do
        [ -d "${skill_dir}" ] || continue
        skill_name="$(basename "${skill_dir}")"
        link_path="${SKILLS_DIR}/${skill_name}"
        # .claude/skills/ から .claude/plugins/{plugin}/skills/{skill}/ への相対パス
        link_target="../plugins/${PLUGIN_NAME}/skills/${skill_name}"

        # 再インストール時は既存リンク・ディレクトリを削除
        if [ -L "${link_path}" ] || [ -e "${link_path}" ]; then
            rm -rf "${link_path}"
        fi

        ln -s "${link_target}" "${link_path}"
        SKILL_COUNT=$((SKILL_COUNT + 1))
    done
fi

# -----------------------------------------------------------------------
# 完了報告
# -----------------------------------------------------------------------
echo ""
echo "✓ '${PLUGIN_NAME}' installed: ${SKILL_COUNT} skill(s)"
echo "  Plugin files : ${PLUGIN_DST}"
echo "  Skills       : ${SKILLS_DIR}/*  (symlinks)"
echo ""

# .gitignore の案内
GITIGNORE="${TARGET_DIR}/.gitignore"
if ! grep -qF ".claude/plugins/" "${GITIGNORE}" 2>/dev/null; then
    echo "Tip: .gitignore に以下を追加することを推奨します:"
    echo "  echo '.claude/plugins/' >> ${GITIGNORE}"
fi
