#!/usr/bin/env bash
# Generated by /plugin-installer-creator — 再生成: このプロジェクトで /plugin-installer-creator を実行
#
# ターゲットプロジェクトからプラグインをアンインストールする。
#
# Usage: uninstall_plugin.sh <plugin_name> [target_dir]
#   plugin_name : アンインストールするプラグイン名（例: forge, anvil）
#   target_dir  : 対象プロジェクトルート（省略時: カレントディレクトリ）

set -euo pipefail

# -----------------------------------------------------------------------
# 引数チェック
# -----------------------------------------------------------------------
PLUGIN_NAME="${1:-}"
TARGET_DIR="${2:-.}"

if [ -z "${PLUGIN_NAME}" ]; then
    echo "Usage: uninstall_plugin.sh <plugin_name> [target_dir]" >&2
    exit 1
fi

TARGET_DIR="$(cd "${TARGET_DIR}" && pwd)"
PLUGIN_DST="${TARGET_DIR}/.claude/plugins/${PLUGIN_NAME}"
SKILLS_DIR="${TARGET_DIR}/.claude/skills"

echo "Uninstalling '${PLUGIN_NAME}' from ${TARGET_DIR}"

REMOVED=0

# -----------------------------------------------------------------------
# Step 1: .claude/plugins/{plugin}/ を削除
# -----------------------------------------------------------------------
if [ -d "${PLUGIN_DST}" ]; then
    rm -rf "${PLUGIN_DST}"
    echo "  Removed: ${PLUGIN_DST}"
    REMOVED=$((REMOVED + 1))
else
    echo "  Not found: ${PLUGIN_DST} (skip)"
fi

# -----------------------------------------------------------------------
# Step 2: .claude/skills/ 内のシンボリックリンクのうち
#         リンク先が plugins/{plugin}/ を指すものをすべて削除
# -----------------------------------------------------------------------
if [ -d "${SKILLS_DIR}" ]; then
    while IFS= read -r -d '' link; do
        target="$(readlink "${link}" 2>/dev/null || true)"
        if echo "${target}" | grep -q "plugins/${PLUGIN_NAME}/"; then
            rm -rf "${link}"
            echo "  Removed: ${link}"
            REMOVED=$((REMOVED + 1))
        fi
    done < <(find "${SKILLS_DIR}" -maxdepth 1 -type l -print0 2>/dev/null)
fi

# -----------------------------------------------------------------------
# 完了報告
# -----------------------------------------------------------------------
echo ""
if [ "${REMOVED}" -eq 0 ]; then
    echo "Nothing to remove for '${PLUGIN_NAME}'."
else
    echo "✓ '${PLUGIN_NAME}' uninstalled (${REMOVED} item(s) removed)."
fi
