#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
forge 同梱 ToC のソース文書の内容 checksums（sha256）を生成する。

`plugins/forge/toc/rules/rules_toc.yaml`（doc-advisor 生成物のコピー配布）が
実ファイル集合・内容と同期しているかを、mtime ではなく内容 hash で検証するために使う。

- `update-forge-toc` skill は ToC コピーと同一操作にするため `finalize_toc.py`
  （本スクリプトの checksums 計算ロジックを再利用する）を呼ぶ
- `tests/forge/doc_structure/test_forge_toc_freshness.py` が本スクリプトの出力を
  再計算し、コミット済み checksums ファイルと突き合わせて ToC 更新忘れを検出する

使用例:
    python3 generate_toc_checksums.py --doc-structure .claude/skills/update-forge-toc/forge_doc_structure.yaml
    python3 generate_toc_checksums.py --doc-structure <path> --output plugins/forge/toc/rules/.toc_checksums.yaml
"""

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
RESOLVE_SCRIPT = (
    SCRIPT_DIR / 'resolve_doc_structure.py'
)

HEADER_LINES = [
    '# Auto-generated by update-forge-toc skill - do not edit directly',
    '# Content-hash checksums of forge 内蔵 docs (rules_toc.yaml のソース文書一覧)',
    '# 検証: tests/forge/doc_structure/test_forge_toc_freshness.py',
]


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--doc-structure', required=True,
        help='rules 対象パスを解決する .doc_structure.yaml 互換ファイル',
    )
    parser.add_argument(
        '--project-root', default='.',
        help='プロジェクトルート（省略時はカレントディレクトリ）',
    )
    parser.add_argument(
        '--output',
        help='出力先ファイルパス（省略時は標準出力に書き出す）',
    )
    return parser.parse_args()


def resolve_paths(doc_structure_path, project_root):
    """resolve_doc_structure.py を呼び出し、rules 対象パス一覧（ソート済み）を取得する。"""
    cmd = [
        sys.executable, str(RESOLVE_SCRIPT),
        '--type', 'rules',
        '--doc-structure', doc_structure_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=project_root)
    if result.returncode != 0:
        raise RuntimeError(f'resolve_doc_structure.py が失敗しました: {result.stderr}')

    data = json.loads(result.stdout)
    if data.get('status') != 'ok':
        raise RuntimeError(data.get('message', 'resolve_doc_structure.py が status: ok 以外を返しました'))
    return sorted(data['rules'])


def sha256_of_file(path):
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def render_checksums(paths, checksums):
    lines = list(HEADER_LINES)
    lines.append(f'file_count: {len(paths)}')
    lines.append('checksums:')
    for path in paths:
        lines.append(f'  {path}: {checksums[path]}')
    return '\n'.join(lines) + '\n'


def main():
    args = parse_args()
    project_root = Path(args.project_root).resolve()

    try:
        paths = resolve_paths(args.doc_structure, str(project_root))
    except RuntimeError as e:
        print(json.dumps({'status': 'error', 'message': str(e)}, ensure_ascii=False))
        return 1

    checksums = {}
    for rel_path in paths:
        full_path = project_root / rel_path
        if not full_path.is_file():
            print(json.dumps(
                {'status': 'error', 'message': f'ファイルが存在しません: {rel_path}'},
                ensure_ascii=False,
            ))
            return 1
        checksums[rel_path] = sha256_of_file(full_path)

    content = render_checksums(paths, checksums)

    if args.output:
        output_path = project_root / args.output
        output_path.write_text(content, encoding='utf-8')
        print(json.dumps(
            {'status': 'ok', 'output': args.output, 'file_count': len(paths)},
            ensure_ascii=False,
        ))
    else:
        sys.stdout.write(content)

    return 0


if __name__ == '__main__':
    sys.exit(main())
